/* Lexora Curriculum Engine v3 — shared state/audio services, curriculum-aware child renderers. */
window.LexoraCurriculumEngine = (function () {
  function qs(root, selector) { return root.querySelector(selector); }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; } ); }
  function tone(kind) { try { var ctx=tone.ctx||(tone.ctx=new (window.AudioContext||window.webkitAudioContext)()), compressor=tone.compressor||(tone.compressor=(function(){var c=ctx.createDynamicsCompressor();c.threshold.value=-18;c.knee.value=12;c.ratio.value=4;c.attack.value=.006;c.release.value=.18;c.connect(ctx.destination);return c;})()); if(ctx.state==='suspended')ctx.resume(); var now=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),isDrum=String(kind).indexOf('drum')>=0,isClap=String(kind).indexOf('tap')>=0||String(kind).indexOf('clap')>=0; o.type=isDrum?'sine':isClap?'square':'triangle'; o.frequency.setValueAtTime(isDrum?145:isClap?620:880,now); o.frequency.exponentialRampToValueAtTime(isDrum?58:isClap?860:1320,now+.18); g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(isDrum?.46:.34,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+.25);o.connect(g).connect(compressor);o.start(now);o.stop(now+.28);return true;}catch(e){return false;} }
  function duration(kind) { return String(kind).indexOf('banana')>=0?900:String(kind).indexOf('drum')>=0?420:650; }
  var cache={};
  function preload(path) { if(!path||path.indexOf('synthetic:')===0||cache[path])return;var a=new Audio(path);a.preload='auto';cache[path]=a; }
  function play(path) { if(!path||path.indexOf('synthetic:')===0)return Promise.resolve(false);preload(path);var a=cache[path];a.currentTime=0;try{var finished=new Promise(function(resolve){var done=function(v){a.removeEventListener('ended',onEnded);a.removeEventListener('error',onError);resolve(v);},onEnded=function(){done(true);},onError=function(){done(false);};a.addEventListener('ended',onEnded,{once:true});a.addEventListener('error',onError,{once:true});setTimeout(function(){done(true);},5000);});return Promise.resolve(a.play()).then(function(){return finished;}).catch(function(){return false;});}catch(e){return Promise.resolve(false);} }
  function shuffle(a){var copy=a.slice();for(var i=copy.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=copy[i];copy[i]=copy[j];copy[j]=t;}return copy;}
  var css='<style>.family-shell{width:100%}.family-badge{display:inline-block;margin:8px 0;padding:6px 11px;border:1px solid rgba(201,162,76,.35);border-radius:99px;color:#e8d9b5;font-size:10px;letter-spacing:.08em;text-transform:uppercase}.family-mode{width:100%;margin:14px 0;padding:15px;border:1px solid rgba(201,162,76,.24);border-radius:18px;background:rgba(201,162,76,.07);text-align:center}.family-mode strong{display:block;color:#e8d9b5}.family-mode small{display:block;margin-top:5px;color:#9a98a0}.family-items{display:flex;justify-content:center;gap:12px;margin-top:12px}.family-item{min-width:92px;min-height:72px;padding:10px;border:1px solid #25242a;border-radius:16px;background:#17171c;color:#f1eee7;font-size:28px}.family-item.selected{border-color:#c9a24c;box-shadow:0 0 0 3px rgba(201,162,76,.16)}.family-beats{display:flex;justify-content:center;gap:8px;margin:14px 0}.family-beat{width:25px;height:25px;border-radius:50%;background:#c9a24c;opacity:.35}.family-beat.active{opacity:1;transform:translateY(-5px)}.blend-bubbles{display:flex;justify-content:center;align-items:center;gap:8px;margin:14px 0}.blend-bubble{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#c9a24c;color:#1a1408;font-weight:750}.blend-arrow{color:#e8d9b5;font-size:20px}.family-shell .engine-choices{margin-top:12px}.listen-icon{width:32px;height:32px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.engine-listen.playing .listen-icon{animation:listenPulse .8s ease-in-out infinite}.engine-listen{display:grid;place-items:center}.engine-listen[aria-label="Replay sound"]:after{content:"↻";position:absolute;margin:35px 0 0 32px;font-size:14px;color:#e8d9b5}@keyframes listenPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.12)}}@media(prefers-reduced-motion:reduce){.engine-listen.playing .listen-icon{animation:none}}</style>';
  function choiceButtons(choices){return shuffle(choices).map(function(c){return '<button class="engine-choice" data-answer="'+esc(c.id)+'" aria-label="'+esc(c.label)+'"><span class="engine-visual">'+esc(c.visual)+'</span><span class="engine-choice-label">'+esc(c.label)+'</span></button>';}).join('');}
  function familyMarkup(spec, activity, choices){
    var r=spec.rendererId, mode='', visual=activity.heroVisual||'👂';
    if(r==='sound-attention'){mode='<div class="family-mode" data-family="sound-attention"><strong>Listen, compare, and match</strong><small>The sound itself is the target.</small><div class="family-items">'+choices.map(function(c){return '<button class="family-item" data-sound-source="'+esc(c.sound||c.id)+'" aria-label="Hear '+esc(c.label)+'">'+esc(c.visual)+'</button>';}).join('')+'</div></div>';}
    else if(r==='rhyming-syllables'){mode='<div class="family-mode" data-family="rhyming-syllables"><strong>'+esc(spec.interactionMode==='beat-units'?'Hear the word parts':'Hear the word relationship')+'</strong><small>Listen first; the pictures carry the meaning.</small><div class="family-beats" id="familyBeats"></div></div>';}
    else if(r==='oral-blending'){mode='<div class="family-mode" data-family="oral-blending"><strong>Put the sounds together</strong><small>Hear each part, then hear the whole word.</small><div class="blend-bubbles" id="blendBubbles"><span class="blend-bubble">•</span><span class="blend-arrow">+</span><span class="blend-bubble">•</span><span class="blend-arrow">→</span><span class="blend-bubble">?</span></div></div>';}
    return '<div class="engine-room family-shell" data-renderer="'+esc(r)+'">'+css+'<header class="engine-top"><button class="engine-back" id="engineBack" aria-label="Back to my learning space">‹</button><span class="engine-step">'+spec.progress.position+' of '+spec.progress.totalLessons+'</span><button class="engine-mute" id="engineMute" aria-label="Audio on">◖</button></header><div class="engine-progress" aria-label="Lesson '+spec.progress.position+' of '+spec.progress.totalLessons+'"><i style="width:'+Math.round(spec.progress.position/spec.progress.totalLessons*100)+'%"></i></div><main class="engine-scene"><div class="engine-kicker">'+esc(spec.title)+'</div><h1>'+esc(spec.title)+'</h1><p class="engine-instruction">'+esc(spec.instruction)+'</p><div class="family-badge">'+esc(spec.unitTitle||r)+'</div><div class="engine-guide" aria-hidden="true">'+esc(visual)+'</div><div class="engine-word-card"><strong>'+esc(r==='oral-blending'?'Blend':'Listen')+'</strong><span>'+esc(activity.prompt)+'</span></div><button class="engine-listen" id="engineListen" aria-label="Listen" title="Listen"><svg class="listen-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5z"/><path d="M15.5 8.5a5 5 0 0 1 0 7M18 5.8a9 9 0 0 1 0 12.4"/></svg></button><div class="engine-audio-label" id="engineAudioLabel">Listen</div><div class="engine-fallback hidden" id="engineFallback">Watch the pictures and follow the visual steps.</div>'+mode+'<div class="engine-choices hidden" id="engineChoices">'+choiceButtons(choices)+'</div><div class="engine-choice-prompt hidden" id="enginePrompt">'+esc(activity.prompt)+'</div><div class="engine-feedback" id="engineFeedback"></div><button class="engine-retry hidden" id="engineRetry">Listen again</button><button class="engine-continue hidden" id="engineContinue">Keep going</button></main><section class="engine-complete" id="engineComplete"><div><div class="engine-check">✓</div><h2>'+esc(spec.feedback.complete)+'</h2><button class="engine-finish" id="engineFinish">Back to my space</button></div></section></div>';
  }
  function mount(options){var root=document.querySelector(options.root||'#lessonRoot');return fetch(options.specUrl).then(function(r){return r.json();}).then(function(spec){var activity=spec.activity,position=spec.progress.position,total=spec.progress.totalLessons,progress=window.LexoraProgress,choices=activity.choices||[],renderer=spec.rendererId;if(!renderer||!spec.interactionContract||!spec.interactionContract.id){root.innerHTML='<p role="alert">This lesson is missing an executable interaction contract.</p>';throw new Error('Missing renderer contract for '+spec.id);}var expectedId=sessionStorage.getItem('lexoraExpectedLesson'),expectedRenderer=sessionStorage.getItem('lexoraExpectedRenderer');if(expectedId&&expectedId!==spec.id){root.innerHTML='<p role="alert">This lesson does not match the selected lesson. Please return to your learning space.</p>';throw new Error('Lesson identity mismatch: '+expectedId+' vs '+spec.id);}if(expectedRenderer&&expectedRenderer!==spec.rendererId){root.innerHTML='<p role="alert">This activity does not match the selected curriculum experience.</p>';throw new Error('Renderer identity mismatch: '+expectedRenderer+' vs '+spec.rendererId);}sessionStorage.removeItem('lexoraExpectedLesson');sessionStorage.removeItem('lexoraExpectedRenderer');if(progress)progress.markIntroduced(position,{strand:spec.strand,stage:spec.stage,unitId:spec.unitId,rendererId:renderer});root.innerHTML=familyMarkup(spec,activity,choices);var listen=qs(root,'#engineListen'),choicesEl=qs(root,'#engineChoices'),prompt=qs(root,'#enginePrompt'),feedback=qs(root,'#engineFeedback'),retry=qs(root,'#engineRetry'),cont=qs(root,'#engineContinue'),label=qs(root,'#engineAudioLabel'),fallback=qs(root,'#engineFallback'),complete=qs(root,'#engineComplete'),muted=false,revealed=false;preload(spec.audio&&spec.audio.instruction);preload(spec.audio&&spec.audio.retry);preload(spec.audio&&spec.audio.success);
      function renderBeats(){var beats=qs(root,'#familyBeats');if(!beats)return;var count=activity.beats||((activity.targetSound||'').indexOf('banana')>=0?3:2);beats.innerHTML=Array.from({length:count},function(_,i){return '<span class="family-beat" data-beat="'+i+'"></span>';}).join('');}
      function reveal(){revealed=true;listen.classList.remove('playing');label.textContent=muted?'Audio is off':'Replay sound';choicesEl.classList.remove('hidden');prompt.classList.remove('hidden');if(renderer==='rhyming-syllables')renderBeats();}
      function playTarget(){if(muted){fallback.classList.remove('hidden');reveal();return;}label.textContent='Listening…';listen.classList.add('playing');var ok=tone(activity.targetSound||activity.correctAnswerId);if(renderer==='rhyming-syllables'&&spec.interactionMode==='beat-units'){renderBeats();Array.prototype.forEach.call(root.querySelectorAll('.family-beat'),function(b,i){setTimeout(function(){b.classList.add('active');setTimeout(function(){b.classList.remove('active');},220);},i*260);});}setTimeout(function(){if(!ok)fallback.classList.remove('hidden');reveal();},duration(activity.targetSound||activity.correctAnswerId));}
      function listenFlow(){fallback.classList.add('hidden');label.textContent='Listening to the directions…';play(spec.audio&&spec.audio.instruction).then(function(ok){if(!ok)fallback.classList.remove('hidden');setTimeout(playTarget,ok?50:0);});}
      listen.addEventListener('click',function(){if(!revealed)listenFlow();else playTarget();});qs(root,'#engineMute').addEventListener('click',function(e){muted=!muted;e.currentTarget.setAttribute('aria-label',muted?'Audio off':'Audio on');if(muted){fallback.classList.remove('hidden');reveal();}else label.textContent='Replay sound';});
      Array.prototype.forEach.call(root.querySelectorAll('[data-sound-source]'),function(btn){btn.addEventListener('click',function(){tone(btn.dataset.soundSource);btn.classList.add('selected');setTimeout(function(){btn.classList.remove('selected');},300);});});
      Array.prototype.forEach.call(root.querySelectorAll('.engine-choice'),function(choice){choice.addEventListener('click',function(){Array.prototype.forEach.call(root.querySelectorAll('.engine-choice'),function(item){item.disabled=true;});var correct=choice.dataset.answer===activity.correctAnswerId;if(progress)progress.recordEvidence(position,{attempt:true,correct:correct,replay:!correct,supportLevel:correct?'independent':'supported',rendererId:renderer,unitId:spec.unitId});if(correct){choice.classList.add('correct');feedback.textContent=spec.feedback.correct;feedback.classList.add('success');if(renderer==='oral-blending'){var bubbles=qs(root,'#blendBubbles');if(bubbles)bubbles.classList.add('selected');}cont.classList.remove('hidden');cont.classList.add('attention');play(spec.audio&&spec.audio.success);}else{choice.classList.add('wrong');feedback.textContent=spec.feedback.incorrect;feedback.classList.add('retry-state');retry.classList.remove('hidden');retry.classList.add('attention');setTimeout(function(){choice.classList.remove('wrong');Array.prototype.forEach.call(root.querySelectorAll('.engine-choice'),function(item){item.disabled=false;});},500);}});});
      retry.addEventListener('click',function(){retry.classList.add('hidden');retry.classList.remove('attention');playTarget();});cont.addEventListener('click',function(){cont.classList.remove('attention');complete.classList.add('open');});qs(root,'#engineBack').addEventListener('click',function(){location.href='child-home-early.html';});qs(root,'#engineFinish').addEventListener('click',function(){if(progress){progress.markComplete(position);location.href=progress.nextLessonUrl();}else location.href='child-home-early.html';});return spec;});}
  return {mount:mount};
})();
